GET http://localhost:4000/user

###

POST  http://localhost:4000/user/userlogin
Content-Type: application/json

{
    "email": "hans@hans.se",
    "password": "hans"  
}

###
POST http://localhost:4000/user
Content-Type: application/json

{
    "name": "Greta",
    "email": "greta@hans.se",
    "password": "greta",
    "subStatus": true 
}

###

DELETE http://localhost:4000/user/628fbdcb236fac470936b7c2

###

PATCH http://localhost:4000/user
Content-Type: application/json

 {
    "_id": "62b3fbe016dc8e3b05a6dc4a",
    "subStatus": true 
 }

###

GET http://localhost:4000/user/62b3fbe016dc8e3b05a6dc4a