GET http://localhost:4000/user

###

POST  http://localhost:4000/user/userlogin
Content-Type: application/json

{
    "email": "hans@hans.se",
    "password": "hans"  
}

###
POST http://localhost:4000/user
Content-Type: application/json

{
    "name": "Hans",
    "email": "hans@hans.se",
    "password": "hans",
    "subStatus": false 
}

###

DELETE http://localhost:4000/user/628fbdcb236fac470936b7c2

###

PUT http://localhost:4000/user
Content-Type: application/json

 {
    "_id": "6293bee904d4566c8419d75b",
    "subStatus": false 
 }

